/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MeasurementsRouteImport } from './routes/measurements'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as PhotosRouteImport } from './routes/photos'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as WorkoutRouteImport } from './routes/workout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MeasurementsRoute = MeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosRoute = PhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/profile': typeof ProfileRoute
  '/program': typeof ProgramRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/profile': typeof ProfileRoute
  '/program': typeof ProgramRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/measurements': typeof MeasurementsRoute
  '/nutrition': typeof NutritionRoute
  '/photos': typeof PhotosRoute
  '/profile': typeof ProfileRoute
  '/program': typeof ProgramRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/measurements'
    | '/nutrition'
    | '/photos'
    | '/profile'
    | '/program'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/measurements'
    | '/nutrition'
    | '/photos'
    | '/profile'
    | '/program'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/measurements'
    | '/nutrition'
    | '/photos'
    | '/profile'
    | '/program'
    | '/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  MeasurementsRoute: typeof MeasurementsRoute
  NutritionRoute: typeof NutritionRoute
  PhotosRoute: typeof PhotosRoute
  ProfileRoute: typeof ProfileRoute
  ProgramRoute: typeof ProgramRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/measurements': {
      id: '/measurements'
      path: '/measurements'
      fullPath: '/measurements'
      preLoaderRoute: typeof MeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos': {
      id: '/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof PhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  MeasurementsRoute: MeasurementsRoute,
  NutritionRoute: NutritionRoute,
  PhotosRoute: PhotosRoute,
  ProfileRoute: ProfileRoute,
  ProgramRoute: ProgramRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
